// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities;

public partial class Product
{
    public int ProductsId { get; set; }

    public int CategoryId { get; set; }

    public string ProductsName { get; set; }

    public string ProductsDescreption { get; set; }

    public decimal Price { get; set; }

    public string ImgUrl { get; set; }

    public string ImgUrl2 { get; set; }

    public string Color { get; set; }

    public string Material { get; set; }

    public int Quantity { get; set; }

    public bool IsActive { get; set; }

    public virtual Category Category { get; set; }

    public virtual ICollection<OrdersItem> OrdersItems { get; set; } = new List<OrdersItem>();
}